spring:
    main:
      banner-mode: log
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1987
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect